services:
    studioartlan.twig.syng_extension:
        class: StudioArtlan\SyngBundle\Twig\SyngExtension
        tags: [{ name: twig.extension }]

    studioartlan.syng_config:
        class: StudioArtlan\SyngBundle\Services\SyngConfig
        arguments: ["@kernel"]
